### ISSUE TITLE
setOnClickListener not working with setOnActionsListener

### ISSUE THREAD

**Issue by Gazzx** [arman-sar/SwipeLayout#2]
Problem :
I can't listen for the recyclerview item click, the swipe shouldn't start as soon as we click on the item

**Comment by SharyRajpoot** [comment]
I have the same problem, I can't click on an item. its like click event is removed or disabled.
but one thing even if I don't swipe the item to the left and click on the above of the item at the right side, then action_delete still calls click ??? major issue well now looking to try another lib.

**Comment by zerobranch** [comment]
1. To listen for the click on an item, you can specify setOnClickListener for the item you specified as in `app:draggedItem`.
2. The library does not manage your views that you specify in `app:draggedItem`, `app:rightItem`, or `app:leftItem`. To prevent the false click from being triggered, you need to specify the following parameters for your draggedItem:
```
android:focusable="true"
android:clickable="true"
```

**Comment by SharyRajpoot** [comment]
Very Very **late** responded but I have managed to do this my own...
mean by make own class and using the built-in recycler view feature.

Thanks anyway. :-)

**Comment by aytajde** [comment]
currently facing this issue and nothing helps. dont know what to do
