### ISSUE TITLE
Open single at a time 

### ISSUE THREAD

**Issue by BhattKandarp** [arman-sar/SwipeLayout#3]
Hello @arman-sar is there any way in your code to open only one swipe at a time  in recyclerview.
I tried with this : app:isTogether ="false" but didn't get any change .
please help me for the same .
wants to maintain position if i want to open other one that time opened swipe menu is should be closed.

**Comment by zerobranch** [comment]
Hello @BhattKandarp!
SwipeLayout is just a view component. In RecyclerView, this component will be separate for each item in the list.

Therefore, you can close the first SwipeLayout when opening the second in the following ways:
1. save the position of the previous element and call the SwipeLayout.close method on it.
2. update the RecyclerView by calling notifyDataSetChanged or notifyItemChanged.
